### ISSUE TITLE
Only update the redirects field when a new slug is "published"

### ISSUE THREAD

**Issue by fcisio** [marcelofinamorvieira/datocms-plugin-slug-redirects#1]
Hi, I was wondering if the behavior of this plugin could be adjusted.

Currently, the redirects field is updated every time the slug changes.
This becomes a problem if the app is redeployed before the affected record is published.
It essentially creates a redirect to a page that doesn't yet exist.

Only updating the redirects field when the affected record is published would solve this issue.

---

If not possible, I will probably fork this project. Please let me know if you found reasons why using [onBeforeItemsPublish](https://www.datocms.com/docs/plugin-sdk/event-hooks#onBeforeItemsPublish) instead of [onBeforeItemUpsert](https://www.datocms.com/docs/plugin-sdk/event-hooks#onBeforeItemUpsert) would not be advisable.

Thanks.

**Comment by marcelofinamorvieira** [comment]
Hello @fcisio i've added a toggle "Only add redirects upon record publish" on the plugin configuration page:

![image](https://user-images.githubusercontent.com/44898680/233802530-d71daf4c-769a-4319-a01c-4c6f19f58d37.png)


If active, you will get the behavior you're looking for.

I've also published it as v0.4.0 on the marketplace, and you can update it directly from your plugin tab :) 

https://github.com/marcelofinamorvieira/datocms-plugin-slug-redirects/commit/6c5292bf2af2c3828cf900155b78b79a597a7199

**Comment by fcisio** [comment]
Even better! thanks!

**Comment by fcisio** [comment]
Hey, sorry to bring this up again.
I think the new mode doesn't behave as expected.

The array seems to be appended in reverse or something.

### current

```json
{
  {
    "source": "first-of-them-all-01", // should be "first-of-them-all"
    "destination": "first-of-them-all", // should be "first-of-them-all-01"
    "urlPrefix": "/posts/",
    "recordID": "133731803"
  },
  {
    "source": "third-post-01", // should be "third-post"
    "destination": "third-post", // should be "third-post-01"
    "urlPrefix": "/posts/",
    "recordID": "135975908"
  },
  {
    "source": "third-post-02", // right value
    "destination": "third-post-01", // should be "third-post-03"
    "urlPrefix": "/posts/",
    "recordID": "135975908"
  }
}
```
